# Generated by Django 4.1.3 on 2022-11-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koaladb',
            name='dob',
        ),
    ]
