# Generated by Django 4.1.3 on 2022-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koaladb',
            name='dob',
            field=models.DateField(null=True, verbose_name='Koalas D.O.B if known'),
        ),
    ]
