# Generated by Django 4.1.3 on 2022-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_koaladb_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koaladb',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Koalas D.O.B if known else: leave blank'),
        ),
    ]
