# Generated by Django 4.1.3 on 2022-11-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_koaladb_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KoalaDB',
        ),
    ]
